// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ7_7t2vlUBFzc8ebAuS5wj2Zl7Mit8_0',
    appId: '1:502955151932:web:dd54480ef301068419e939',
    messagingSenderId: '502955151932',
    projectId: 'eye-tracking-data-collection',
    authDomain: 'eye-tracking-data-collection.firebaseapp.com',
    storageBucket: 'eye-tracking-data-collection.firebasestorage.app',
    measurementId: 'G-6MDX5RKFC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvn8etmHXWq-MYnn5oTKcT0cp6L7MIrsQ',
    appId: '1:502955151932:android:bf50c19eb1155c8319e939',
    messagingSenderId: '502955151932',
    projectId: 'eye-tracking-data-collection',
    storageBucket: 'eye-tracking-data-collection.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ7_7t2vlUBFzc8ebAuS5wj2Zl7Mit8_0',
    appId: '1:502955151932:web:816cdc4444159e3919e939',
    messagingSenderId: '502955151932',
    projectId: 'eye-tracking-data-collection',
    authDomain: 'eye-tracking-data-collection.firebaseapp.com',
    storageBucket: 'eye-tracking-data-collection.firebasestorage.app',
    measurementId: 'G-1B0EHRSWZW',
  );
}
